apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-alerts
  namespace: monitoring
spec:
  groups:
  - name: nginx.rules
    rules:
    - alert: NginxHighRequestRate
      expr: rate(nginx_http_requests_total[5m]) > 50
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "NGINX High Request Rate"
        description: "NGINX has more than 50 requests in 5 minutes"
