apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vmykhailyk/mynginx.git'
    targetRevision: main
    path: monitoring
    helm:
      valueFiles:
        - monitoring/prometheus/prometheus-values.yaml
        - monitoring/grafana/grafana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
